dir:
  input_root: inputs/IndoorLRS/
  output_root: outputs/IndoorLRS/
  pretrain_root: ../../weights/resnet_50_pri3d.pth

data:
  depth_threshold: 0.1
  img_feats_dim: 128
  num_images: 3
  dataset: IndoorLRS
  benchmark_name: IndoorLRS       # IndoorLRS
  fusion_type: complement         # average, complement or random
