dir:
  output_folder_name: outputs
  exp_name: 3DMatch

seed: 7351

data:
  dataset_root: data/3DMatch

train:
  batch_size: 1
  num_workers: 8
  point_limit: 30000
  use_augmentation: true
  augmentation_noise: 0.005
  augmentation_rotation: 1.0

test:
  batch_size: 1
  num_workers: 8
  point_limit: null

eval:
  acceptance_overlap: 0.0
  acceptance_radius: 0.10
  inlier_ratio_threshold: 0.05
  rmse_threshold: 0.20
  rre_threshold: 15.0
  rte_threshold: 0.3

ransac:
  distance_threshold: 0.05
  num_points: 3
  num_iterations: 50000

optim:
  lr: 0.0001
  lr_img: 0.0001
  lr_decay: 0.95
  lr_decay_steps: 1
  weight_decay: 0.000001
  max_epoch: 20
  grad_acc_steps: 1

kpconv:
  num_stages: 4
  init_voxel_size: 0.025
  kernel_size: 15
  base_radius: 2.5
  base_sigma: 2.0
  group_norm: 32
  input_dim: 129
  init_dim: 256
  output_dim: 256

model:
  ground_truth_matching_radius: 0.05
  num_points_in_patch: 64
  num_sinkhorn_iterations: 100

coarse_matching:
  num_targets: 128
  overlap_threshold: 0.1
  num_correspondences: 256
  dual_normalization: true

geotrans:
  input_dim: 4096
  hidden_dim: 256
  output_dim: 256
  num_heads: 4
  blocks: ['self', 'cross', 'self', 'cross', 'self', 'cross']
  sigma_d: 0.2
  sigma_a: 15
  angle_k: 3
  reduction_a: max

fine_matching:
  topk: 3
  acceptance_radius: 0.1
  mutual: true
  confidence_threshold: 0.05
  use_dustbin: false
  use_global_score: false
  correspondence_threshold: 3
  correspondence_limit: null
  num_refinement_steps: 5

coarse_loss:
  positive_margin: 0.1
  negative_margin: 1.4
  positive_optimal: 0.1
  negative_optimal: 1.4
  log_scale: 24
  positive_overlap: 0.1

fine_loss:
  positive_radius: 0.05

loss:
  weight_coarse_loss: 1.0
  weight_fine_loss: 1.0
  weight_img_matching_loss: 1.0